clusters updated

diff --git a/dcw b/dcw
--- a/dcw
+++ b/dcw
@@ -6,13 +6,21 @@ if [ ! -d $WORK_DIR ]; then mkdir -p $WORK_DIR ; fi
 if [ ! -e etc/config.conf ]; then
    echo "you are not at the right dirtory yet..."
    exit 1
+else
+   source etc/config.conf
 fi
-source etc/config.conf
 if [ ! -e etc/common.sh ]; then
    echo "the etc\/common.sh file is missing..."
    exit 1
+else
+   source etc/common.sh
 fi
-source etc/common.sh
+if [ ! -e etc/pipeline.sh ]; then
+   echo " the etc\/pipeline.sh file is missing..."
+   exit 1
+else
+   source etc/pipeline.sh
+fi
 
 
 git-clone-concourse-docker
